### ISSUE TITLE
KeyError: 'results'

### ISSUE THREAD

**Issue by Superhzf** [quantgalore/option-probability-distribution#1]
Thanks for the code!

When I run the script `option-probability-distribution.py`, Python complains about [this line](https://github.com/quantgalore/option-probability-distribution/blob/main/option-probability-distribution.py#L28). It seems `results ` is not one of the keys. 

If I run the code `request.get(...)`, the returned dict looks like this:
`{'ticker': 'ATVI',
 'queryCount': 0,
 'resultsCount': 0,
 'adjusted': True,
 'status': 'OK',
 'request_id': 'e10a0e60790e8992eb239455c90e34ef'}`

Did I do anything wrong?

**Comment by quantgalore** [comment]
Hi Zach, 

You're all good, this is due to the ticker "ATVI" being retired from Polygon since it is no longer tradeable post-acquisition. I am not sure that the API has historical data on delisted tickers yet. 

Thanks!

**Comment by Superhzf** [comment]
> Hi Zach,
> 
> You're all good, this is due to the ticker "ATVI" being retired from Polygon since it is no longer tradeable post-acquisition. I am not sure that the API has historical data on delisted tickers yet.
> 
> Thanks!

Thank you! I will try a different one.
